---
title: "Week 3 Lab"
author: "Arin Parsa"
date: "5/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-packages, message = FALSE}
library(statsr)
library(dplyr)
library(ggplot2)
```
#Kobe Bryant Dataset

Our investigation will focus on the performance of one player: Kobe Bryant of the Los Angeles Lakers. His performance against the Orlando Magic in the 2009 NBA finals earned him the title Most Valuable Player and many spectators commented on how he appeared to show a hot hand. Let’s load some necessary files that we will need for this lab.

```{r}
data(kobe_basket)

kobe_streak <- calc_streak(kobe_basket$shot)

ggplot(data = kobe_streak, aes(x = length)) +
  geom_histogram(binwidth = 1)

#Question: Which of the following is false about the distribution of Kobe’s streak lengths from the 2009 NBA finals.

#The shortest streak is of length 1.

coin_outcomes <- c("heads", "tails")
sample(coin_outcomes, size = 1, replace = TRUE)

sim_fair_coin <- sample(coin_outcomes, size = 100, replace = TRUE)
table(sim_fair_coin)

#Exercise: In your simulation of flipping the unfair coin 100 times, how many flips came up heads?

sim_unfair_coin <- sample(coin_outcomes, size = 100, replace = TRUE, 
                          prob = c(0.2, 0.8))

table(sim_unfair_coin)

#21 heads

shot_outcomes <- c("H", "M")
sim_basket <- sample(shot_outcomes, size = 1, replace = TRUE)

#Exercise: What change needs to be made to the sample function so that it reflects a shooting percentage of 45%? Make this adjustment, then run a simulation to sample 133 shots.

sim_basket <- sample(shot_outcomes, size = 133, replace = TRUE, c(0.45, 0.55))

#Exercise: Using calc_streak, compute the streak lengths of sim_basket, and save the results in a data frame called sim_streak.
sim_streak <- calc_streak(sim_basket)

#Exercise: Make a plot of the distribution of simulated streak lengths of the independent shooter. What is the typical streak length for this simulated independent shooter with a 45% shooting percentage? How long is the player’s longest streak of baskets in 133 shots?

ggplot(data = sim_streak, aes(length)) + geom_histogram(binwidth = 1)
```